[package]
name = "clipwatch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(unix)'.dependencies]
x11 = "2.19.1"
filedescriptor = "0.8.1"